# NumPy

***Numerical Python***

    Type of array
        <class 'numpy.ndarray'>


    1. a = numpy.array( [ Values ] , dtype= int/float/complex/str)    
            --> To build an array.
    
    2. a.ndim
            --> To find the dimention of array(1,2,3....)
    
    3. a.itemsize
            --> To get the size per item
            
    4. a.shape
            --> To get shape of array (rows,columns)
            
    5. a.reshape(#rows,#columns)
            --> To reshape the current array.
            --> suppose we have array with 3-rows and 5-columns,
                    so this array can be reshaped in multiples of 15(3*5)
                    i.e. (1,15)/(5,3)
                    
    6. numpy.arange(start, end, interval)
    
    7. nimpy.linspace(start,end,cuts)
            --> Cuts the given line into equal segments with given number of cuts.
            
    8. Indexing (Accessing elements from array)
    
            --> array_name[row:row,column:column]
            
            --> a[1:] # elements from row index 1 to end

            --> a[:,1:] # elements from column index 1 to end
    
    9. Broadcasting (process of appling the changes throught the array)

            --> adding 2 to all matrix elements ---> a+2

            --> substracting 2 from all matrix elements ---> a-2

            --> to all matrix elements dividing by 2  ---> a/2

            --> multiplying 2 to all matrix elements ---> a*2

            --> adding elements of two matrices ---> a+b

            --> substracting elements of two matrices ---> a-b

            --> multiplying elements of two matrices ---> a*b 
                        --> # Normal multiplication not the matrix multiplication

            --> dividing elements of two matrices ---> a/b
                        ---> # Normal division not the matrix division
    
    10.Multipling two matrices

            ---> np.dot(a,b)
            

    11. Flatten

            --> To flatten the array ( convert array into 1 dimentional array)
    
    12. np.random.normal(loc=0.0, scale=1.0, size=None)
            --> Draw random samples from a normal (Gaussian) distribution.
            
    13.np.eye(N) optional (M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
            --> Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [1]:
import numpy as np

### How to build an array

In [2]:
a = np.array([10,30,60],dtype= 'int8')

print(type(a),'\n')
print(a,'\n')
print('dimention : ',a.ndim)

<class 'numpy.ndarray'> 

[10 30 60] 

dimention :  1


In [3]:
a = np.array([
    [10,30,60],
    [1,2,3],
    [10,11,12]
],dtype = float)

print(a,'\n')
print('dimention : ',a.ndim)

[[10. 30. 60.]
 [ 1.  2.  3.]
 [10. 11. 12.]] 

dimention :  2


In [4]:
a = np.array([
    [
        [10,30,60],
        [1,2,3],
        [10,11,12]
    ],
    [
        [1,2,3],
        [10,11,12],
        [100,200,300]
    ]],dtype= complex )
print(a,'\n')
print('dimention : ',a.ndim)

[[[ 10.+0.j  30.+0.j  60.+0.j]
  [  1.+0.j   2.+0.j   3.+0.j]
  [ 10.+0.j  11.+0.j  12.+0.j]]

 [[  1.+0.j   2.+0.j   3.+0.j]
  [ 10.+0.j  11.+0.j  12.+0.j]
  [100.+0.j 200.+0.j 300.+0.j]]] 

dimention :  3


In [5]:
a.itemsize

16

In [6]:
a.shape

(2, 3, 3)

### reashape

In [7]:
a.reshape(6,3)

array([[ 10.+0.j,  30.+0.j,  60.+0.j],
       [  1.+0.j,   2.+0.j,   3.+0.j],
       [ 10.+0.j,  11.+0.j,  12.+0.j],
       [  1.+0.j,   2.+0.j,   3.+0.j],
       [ 10.+0.j,  11.+0.j,  12.+0.j],
       [100.+0.j, 200.+0.j, 300.+0.j]])

# To generate sequence of number

    numpy.arange(start, end, interval)

In [8]:
a = np.arange(10,20,2)
a

array([10, 12, 14, 16, 18])

# generate empty array

In [9]:
a = np.empty([3,4], dtype=int)
b = np.empty([3,4], dtype=float)
c = np.empty([3,4], dtype=complex)
d = np.empty([3,4], str)
print('integer')
print(a,'\n')
print('float')
print(b,'\n')
print('complex')
print(c,'\n')
print('str')
print(d,'\n')

integer
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

float
[[9.83668877e-312 2.81617418e-322 0.00000000e+000 0.00000000e+000]
 [2.05833592e-312 1.04082753e-047 5.45004578e-090 9.05970385e-043]
 [1.53393340e-052 2.77387254e+180 6.48224660e+170 4.93432906e+257]] 

complex
[[6.23042070e-307+4.67296746e-307j 1.69121096e-306+1.60219442e-306j
  1.89146896e-307+1.37961302e-306j 1.05699242e-307+8.01097889e-307j]
 [1.78020169e-306+7.56601165e-307j 1.02359984e-306+1.33510679e-306j
  2.22522597e-306+1.33511018e-306j 6.23057689e-307+1.02360120e-306j]
 [8.45559303e-307+8.06613040e-308j 6.89810244e-307+1.22387550e-307j
  2.22522596e-306+8.34423917e-308j 1.11261162e-306+1.78021527e-306j]] 

str
[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']] 



In [10]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Linespace

In [12]:
a = np.linspace(10,19,5,endpoint=False)
a

array([10. , 11.8, 13.6, 15.4, 17.2])

### Accessing the array elements

***NUMPY follows the indexing method***

    a[rows,columns]
    
    a[1:2,1:2]

In [18]:
a = np.arange(0,25,3)
a = a.reshape(3,3)
a

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [26]:
a[0:2:,2:]

array([[ 6],
       [15]])

In [28]:
a[1:] # elements from row index 1 to end

array([[ 9, 12, 15],
       [18, 21, 24]])

In [29]:
a[:,1:] # elements from column index 1 to end

array([[ 3,  6],
       [12, 15],
       [21, 24]])

### Broadcasting

In [30]:
a

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [31]:
a+2

array([[ 2,  5,  8],
       [11, 14, 17],
       [20, 23, 26]])

In [32]:
a-2

array([[-2,  1,  4],
       [ 7, 10, 13],
       [16, 19, 22]])

In [33]:
a/2

array([[ 0. ,  1.5,  3. ],
       [ 4.5,  6. ,  7.5],
       [ 9. , 10.5, 12. ]])

In [34]:
a*2

array([[ 0,  6, 12],
       [18, 24, 30],
       [36, 42, 48]])

In [37]:
b = np.arange(100,1000,100)
b = b.reshape(3,3)

print(b)

print(a)

[[100 200 300]
 [400 500 600]
 [700 800 900]]
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


In [38]:
a+b

array([[100, 203, 306],
       [409, 512, 615],
       [718, 821, 924]])

In [39]:
a-b

array([[-100, -197, -294],
       [-391, -488, -585],
       [-682, -779, -876]])

In [41]:
a*b # Normal multiplication not the matrix multiplication

array([[    0,   600,  1800],
       [ 3600,  6000,  9000],
       [12600, 16800, 21600]])

In [42]:
a/b # Normal division not the matrix division

array([[0.        , 0.015     , 0.02      ],
       [0.0225    , 0.024     , 0.025     ],
       [0.02571429, 0.02625   , 0.02666667]])

### Multipling two matrices

In [45]:
print(a,'\n \n', b)

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]] 
 
 [[100 200 300]
 [400 500 600]
 [700 800 900]]


In [47]:
c = np.dot(a,b)
c

array([[ 5400,  6300,  7200],
       [16200, 19800, 23400],
       [27000, 33300, 39600]])

### Flatten

to flatten the array ( convert array into 1 dimentional array)

In [49]:
c.flatten()

array([ 5400,  6300,  7200, 16200, 19800, 23400, 27000, 33300, 39600])

In [54]:
np.random.normal(5,10,3)

array([ 3.04315186,  7.5443834 , 11.10478966])

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Where

***Indices of the conditioned elements***

In [56]:
a

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [72]:
a = a.flatten()
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [69]:
np.where(a>5)

(array([2, 3, 4, 5, 6, 7, 8], dtype=int64),)

In [73]:
for i in np.where(a>5):
    print(a[i])

[ 6  9 12 15 18 21 24]
